name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privatkey: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /tmp/socialswag-trail/socialswag-lambda-automation/
          sudo -S git pull https://github.com/Ram5535/socialswag-lambda-automation.git
