name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: Ram5535/socialswag-lambda-automation@main
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        port: 22
        script: cd /opt/socialswag-lambda-automation && git pull
