name: Deploy via SSH
on: [workflow_dispatch]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /tmp
          ls -a
        host: ${{ secrets.SSH_HOST_151 }}
        user: ${{ secrets.SSH_USERNAME_151 }}
        key: ${{ secrets.SSH_PVTKEY_151 }}
        port: ${{ secrets.SSH_PORT_151 }}
